#@ load("namespace.lib.yml", "getNamespace")
#@ load("deploy.lib.yml", "getDeploy")
#@ load("service.lib.yml", "getService")
#@ load("ingress.lib.yml", "getIngress")
#@ load("issuer.lib.yml", "getIssuer")
#@ load("conf-map.lib.yml", "getDefaultConfigMap", "getValuesConfigMap")

--- #@ getNamespace()
--- #@ getIssuer()
--- #@ getDeploy()
--- #@ getService()
--- #@ getIngress()
--- #@ getDefaultConfigMap()
#@ configs = getValuesConfigMap()
#@ for/end config in configs:
--- #@ config
